version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-newsapi}
      - POSTGRES_USER=${POSTGRES_USER:-newsapi}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password_123}
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-newsapi}:${POSTGRES_PASSWORD:-dev_password_123}@db:5432/${POSTGRES_DB:-newsapi}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A newsapi worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-newsapi}:${POSTGRES_PASSWORD:-dev_password_123}@db:5432/${POSTGRES_DB:-newsapi}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - db
      - redis

volumes:
  postgres_data:

